services:
  auth_service:
    # image: ehs22n/auth_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    networks:
      - auth_network
    deploy:
      mode: replicated
      replicas: 1           # run 2 instances for load balancing
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "0.5"
      #     memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  auth_network:
    driver: overlay
    attachable: true
